packages:
  - apps/*
  - packages/*
  - components/*


catalog:
  react: ^19.0.0,
  react-dom: ^19.0.0,
  react-router: ^7.1.1,
  tailwind-merge: ^2.6.0,
  tailwindcss-animate: ^1.0.7,
  zod: ^3.23.8,
  autoprefixer: ^10.4.20,
  cross-env: ^7.0.3,
  postcss: ^8.4.49,
  tailwindcss: ^3.4.16,
  typescript: ^5.7.2,
  vite: ^5.4.11,
  vite-tsconfig-paths: ^5.1.4